### ISSUE TITLE
Cannot connect to MSSQL after updating to 10.0 on 2/11

### ISSUE THREAD

**Issue by jjAtNxtPt** [ibis-project/ibis#10818]
### What happened?

When I try to run this line:
`con = ibis.mssql.connect(host="db.host.url", driver="ODBC Driver 17 for SQL Server", database="Master", autocommit=True)`

I get this error:   AttributeError: 'NoneType' object has no attribute 'replace'

This line of code has been in use for months without issue.

### What version of ibis are you using?

ibis-framework                10.0.0

### What backend(s) are you using, if any?

MSSQL and DuckDB

### Relevant log output

```sh
File "C:\Python\Python312\Lib\site-packages\ibis\__init__.py", line 110, in connect
    return backend.connect(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python312\Lib\site-packages\ibis\backends\__init__.py", line 928, in connect
    new_backend.reconnect()
  File "C:\Python\Python312\Lib\site-packages\ibis\backends\__init__.py", line 943, in reconnect
    self.do_connect(*self._con_args, **self._con_kwargs)
  File "C:\Python\Python312\Lib\site-packages\ibis\backends\mssql\__init__.py", line 179, in do_connect
    password=self._escape_special_characters(password),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python312\Lib\site-packages\ibis\backends\mssql\__init__.py", line 188, in _escape_special_characters
    return "{" + value.replace("}", "}}") + "}"
                 ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Thanks for the report, fix is up in #10824.
